name: Lint
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.50.1
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
